[personal]
makepath="/usr/bin/make"
homepath="/home/flvincen"
import="ljk/skwdro"

[clusterparams]
cluster="dahu"
user="vincenfl"
walltime=16
nodes=1
cores=16
name="SkWDRO_probplots"


[logreg]

repeat=1000

[logreg.logrho]
min=-2.0
max=0.0
num=10

[logreg.epsilon]
min=-7.0
max=-2.0
lnum=5

[logreg.d]
val=5

[logreg.n_train]
val=100

[logreg.n_test]
val=10000

[logreg.sigma]
val=1.5

[logreg.n_zeta]
val=10

[logreg.xptype]
baseline=false
regularized=true
hists=true

[portfolio]
repeat=1000

[portfolio.logrho]
min=-3.0
max=3.0
num=5

[portfolio.epsilon]
min=-7.0
max=-2.0
lnum=5

[portfolio.d]
val=5

[portfolio.n_train]
val=100

[portfolio.n_test]
val=10000

[portfolio.sigma]
val=1.5

[portfolio.n_zeta]
val=10
