# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context: {}

package:
  name: skwdro
  version: 1.0.1

source:
- url: https://files.pythonhosted.org/packages/03/a1/0647067b51625185eefce1b8a7e17b125bda347a76882eec2eebadb02329/skwdro-1.0.1.tar.gz
  sha256: 312d4b00d2e9dffc28b51f0bd1c16eb33e474cae70b930d0ad327c6fa9397a26

build:
  script:
    interpreter: bash
    content: |
      python -m pip install .  -vv --no-deps --no-build-isolation

requirements:
  build:
    - git
    - python
    - pip
    - hatchling
  host:
    - hatchling
    - python
    - pip
  run:
    - python
    - cvxopt
    - cvxpy
    - dask
    - numpy
    - pandas
    - scikit-learn >=1.4
    - scipy
    - pytorch
    - pytorch-cuda
    - prodigyopt
    - mechanic-pytorch
  # - furo  # extra == 'docs'
  # - myst-parser  # extra == 'docs'
  # - numpydoc  # extra == 'docs'
  # - sphinx  # extra == 'docs'
  # - sphinx-copybutton  # extra == 'docs'
  # - sphinx-design  # extra == 'docs'
  # - sphinx-gallery  # extra == 'docs'
  # - sphinx-rtd-theme  # extra == 'docs'
  # - joblib  # extra == 'examples'
  # - matplotlib  # extra == 'examples'
  # - seaborn  # extra == 'examples'
  # - torchvision  # extra == 'examples'
  # - tqdm  # extra == 'examples'
  # - wandb  # extra == 'monitor'
  # - mypy  # extra == 'test'
  # - pycodestyle  # extra == 'test'
  # - pytest  # extra == 'test'
  # - pytest-cov  # extra == 'test'
  # - ruff  # extra == 'test'

tests: []

about:
  summary: A Robust ML toolbox
  homepage: https://github.com/iutzeler/skwdro
  license: BSD-3-Clause
  description: |
    SkWDRO is a Python package that offers WDRO versions for a large range of estimators, either by extending scikit-learn estimator or by providing a wrapper for pytorch modules.
  documentation: https://skwdro.readthedocs.io
  repository: https://github.com/iutzeler/skwdro
