r"""
Simple Neural Network
=====================

This example solves a simple binary classification problem using a basic neural network with 2 layers. 

The classification problem is generated by the make_moons dataset generator from scikit--learn.


"""
import numpy as np
import matplotlib.pyplot as plt
from utils.plotting import plot_decision_boundary
import torch as pt
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader


from skwdro.torch import robustify


# %%
# Problem setup
# ~~~~~~~~~~~~~

from sklearn.datasets import make_moons

n = 200

X, y = make_moons(n_samples=n,
                  noise=0.1,
                  random_state=42)

# Visualize the data
import matplotlib.pyplot as plt

plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.RdYlBu);
#plt.show()

# Turn data into tensors
X = pt.tensor(X, dtype=pt.float)
y = pt.tensor(y, dtype=pt.float).unsqueeze(-1)

# Split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    random_state=42)


dataset = DataLoader(TensorDataset(X_train, y_train))




device = "cuda" if pt.cuda.is_available() else "cpu"

# %%
# Polynomial model
# ~~~~~~~~~~~~~~~~

class SimpleNN(nn.Module):
    def __init__(self, in_features, out_features, hidden_units):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(in_features, hidden_units),
            nn.ReLU(),
            nn.Linear(hidden_units, hidden_units),
            nn.ReLU(),
            nn.Linear(hidden_units, out_features),
        )

    def forward(self, x):
        # x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = SimpleNN(in_features=2,
                      out_features=1,
                      hidden_units=5).to(device)


print(model)


loss_fn = nn.BCEWithLogitsLoss()

# Define a sample batch for initialization
sample_batch_x, sample_batch_y = next(iter(dataset))


# Robust loss
robust_loss = robustify( 
            loss_fn,
            model,
            pt.tensor(1.0),
            sample_batch_x, sample_batch_y
        ) # Replaces the loss of the model by the dual WDRO loss

# %%
# Training loop
# ~~~~~~~~~~~~~
pt.manual_seed(42)
epochs=10

# optimizer = pt.optim.AdamW(params=model.parameters(),lr=1e-2)
optimizer = pt.optim.AdamW(params=robust_loss.parameters(),lr=1e-2)


# Training loop
for epoch in range(epochs):
    for batch_x, batch_y in dataset:

        print(batch_y.shape)

        ### Training
        model.train()

        optimizer.zero_grad()
        # loss = loss_fn(model(batch_x.squeeze()), batch_y)
        loss = robust_loss(batch_x, batch_y).mean()
        loss.backward()
        optimizer.step()

        ### Testing
        model.eval() 
        with pt.inference_mode():
            # Forward pass
            test_logits = model(X_test).squeeze()
            test_pred = pt.round(pt.sigmoid(test_logits))
            # Compute the loss
            test_loss = loss_fn(test_logits, y_test)

        # Print
        if epoch % 1 == 0:
            print(f"Epoch: {epoch} | Loss: {loss:.2f} | Test loss: {test_loss:.2f} ")




# Plot decision boundaries for training and test sets
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Train")
plot_decision_boundary(model, X_train, y_train)
plt.subplot(1, 2, 2)
plt.title("Test")
plot_decision_boundary(model, X_test, y_test)
plt.show()