name: doc

on:
  push:
    branches:
#    - main
#    - dev
    - doc/cleanup
  pull_request:
    branches:
#    - main
#    - dev
    - doc/cleanup

concurrency:
  group: ${{ github.ref }}
#  cancel-in-progress: true

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.11'

    - name: Install Hatch
      run: pip install hatch

    - name: Install requirements
      run: pip install -r doc/requirements.txt

    - name: Run tests
      run: make doctest
