name: General setup

on:
  push:
    branches:
    - main
    - dev
    - cleanup
  pull_request:
    branches:
    - main
    - dev

jobs:
  run:
    name: Run setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11'
          cache: 'pip'


    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
        restore-keys:
          ${{ env.pythonLocation }}-

    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
        hatch -e env-test run python -c "import torch as pt; print(pt.cuda.is_available())"

  tests:
    name: Launch Test workflow
    needs: run
    uses: ./.github/workflows/test.yml

  style:
    name: Launch Style workflow
    needs: run
    uses: ./.github/workflows/style.yml

  doctest:
    name: Launch Doc Test workflow
    needs: run
    uses: ./.github/workflows/doc.yml
