name: General setup

on:
  push:
    branches:
    - main
    - dev
    - cleanup
  pull_request:
    branches:
    - main
    - dev

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.11'
          cache: 'pip'


    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
        restore-keys:
          ${{ env.pythonLocation }}-

    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
        hatch -e env-dev shell

    - name: Save cache
      uses: actions/cache/save@v4

  tests:
    needs: run
    uses: ./.github/workflows/test.yml

  style:
    needs: run
    uses: ./.github/workflows/style.yml
