name: test

on:
  workflow_call:

jobs:
  setup:
    name: Launch setup
    uses: ./.github/workflows/setup.yml
    
  run:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11'

    - name: Get cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
        restore-keys:
          ${{ env.pythonLocation }}-
            #
            # - name: Install Hatch
            #   run: pip install hatch

    - name: Run tests
      run: make test
