name: test

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.11' 

    - name: Install Hatch
      run: pip install hatch

    - name: Run tests
      run: make test
